version: '3.9'
services:

  db:
    image: postgres:15
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

  web:
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_value: