# Generated by Django 4.1.6 on 2023-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('title',), 'verbose_name': 'Album'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',), 'verbose_name': 'Artist'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('title',), 'verbose_name': 'Song'},
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.CheckConstraint(check=models.Q(('year__lte', 2023)), name='year_check'),
        ),
        migrations.AddConstraint(
            model_name='songalbumm2m',
            constraint=models.UniqueConstraint(fields=('song', 'album'), name='unique_song_album'),
        ),
    ]
