# Generated by Django 4.1.6 on 2023-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_songalbumm2m_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='album title'),
        ),
    ]
